# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(help_text='e.g Romance , Action , ...', max_length=500)),
                ('reso', models.CharField(choices=[('HD', 'HD'), ('DVD', 'DVD'), ('CAM', 'CAM')], max_length=3, verbose_name='Resolustion')),
                ('release', models.CharField(max_length=4)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200, verbose_name='Image')),
                ('comment_count', models.CharField(editable=False, max_length=5)),
                ('rate_count', models.CharField(editable=False, max_length=1)),
            ],
        ),
    ]
